config/routes.rb
Rails.application.routes.draw do

	root 'comments#index'
	resources :comments, only: [:index, :create]
	get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
	
	get 'signup'  => 'users#new'
	resources :users
	
	get '/login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	acts_as_tree order: 'created_at DESC'
	
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :posts
	
	def index
		@user = User.find(params[:id])
	end
	
	validates_uniqueness_of :username, :message=>"That username is taken."
	validates_uniqueness_of :email, :message=>"A KungAccount with that email already exists."
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user 

	def current_user 
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	
	def require_user 
  		redirect_to '/login' unless current_user 
	end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :require_user, only: [:index, :show]

	def index
    	@comments = Comment.hash_tree
	end

  	def new
  		@comment = Comment.new(parent_id: params[:parent_id])
  	end

   	def create
   		if params[:comment][:parent_id].to_i > 0
    		parent = Comment.find_by_id(params[:comment].delete(:parent_id))
    		@comment = parent.children.build(comment_params)
    		@comment.author = current_user.username
  		else
    		@comment = Comment.new(comment_params)
    		@comment.author = current_user.username
  		end

  		if @comment.save
    		flash[:success] = 'Your comment was successfully added!'
    		redirect_to root_url
  		else
    		render 'new'
  		end
  	end
  	
  	private

	  def comment_params
		params.require(:comment).permit(:title, :body)
	  end
  	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :require_user, only: [:index, :show]
	
	def index
  		@new_post = Post.new
 	 	@all_posts = Post.order(created_at: :desc).all
	end

	def create 
    	@new_post = Post.new(post_params)
    	@new_post.author = current_user.username
    	if @new_post.save 
    		redirect_to '#root_path' 
  		else 
    		render 'new' 
  		end 
	end
  
  private
  	def post_params
    	params.require(:post).permit(:comment)
  	end
  	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	
	def create
  		@user = User.find_by_username(params[:session][:username])
  		if @user && @user.authenticate(params[:session][:password])
    		session[:user_id] = @user.id
    		redirect_to '/'
  		else
    		redirect_to '/signup'
  		end 
	end

	def destroy 
  		session[:user_id] = nil 
  		redirect_to '/' 
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user = User.new
	end
	
	def create 
	  @user = User.new(user_params) 
	  if @user.save 
		session[:user_id] = @user.id 
		redirect_to '/' 
	  else 
		redirect_to '/signup' 
	  end 
	end
	
private
	def user_params
    	params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

	def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="well">
  <h3><%= comment.title %></h3>
  <p class="text-muted"><%= comment.root? ? "Started by" : "Replied by" %> <strong><%= comment.author %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>

  	<blockquote>
  		<p><%= comment.body %></p>
	</blockquote>

<!--	
	<% from_reply_form ||= nil %>
	<% unless from_reply_form %>
  <% if comment.leaf? %>
    <small class="text-muted">There are no replies yet - be the first one to reply!</small>
  <% end %>

-->
  <p><%= link_to 'reply', new_comment_path(comment.id) %></p>
<% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
<!--
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control', required: true %>
  </div>
-->
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
  
  <%= f.hidden_field :parent_id %>

<% end %>

app/views/comments/index.html.erb
<% if current_user %> 
  <ul>
	<li><h3>Welcome, <%= current_user.username %></h3></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  </ul> 
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
  </ul> 
<% end %>

<div class="jumbotron">
  <div class="container">
    <h2>Join a Matt-based discussion!</h2>
    <p>
      <%= link_to 'Add new topic', new_comment_path, class: 'btn btn-default btn-lg' %>
    </p>
  </div>
</div>

<%= comments_tree_for @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mattkungsbirthday.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <link href='https://fonts.googleapis.com/css?family=Mountains+of+Christmas:400,700' rel='stylesheet' type='text/css'>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
</head>
<body>

<div id='title'><%= link_to 'MattKungsBirthday.com', '/' %></div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="container">
<div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
<% if current_user %> 
  <ul>
	<li><h4>Welcome</h4></li>  
    <li><%= current_user.username %></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  </ul> 
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
  </ul> 
<% end %>
</div>

<div class="main">

    <div class="form-horizontal">        
        <%= form_for @new_post do |t| %>
    	<div class="form-group">
    		<div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
        	<%= t.text_area :comment, id:'text-box' %> <br>
        	</div>
        </div>
        <div class="form-group">
        	<div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
			<%= t.submit "Post", id:'post', class: "btn btn-default"%>
        	</div>
        </div>
        <% end %>
        
        <ul class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
          <% @all_posts.each do |p| %>
  			<div class="comment">
  			<li><%= word_wrap(p.comment, line_width: 5) %><br><br>
			<div class="tag">
			<%= p.created_at %>
			by <%= p.author %></li>
			</div>
			<% end %>
  			</div>
		</ul>

</div>
</div>

app/views/users/new.html.erb
  <div class="container">
  	
  	<div class="prompt">
        	<%= image_tag "bee.png", width:"62px", height:"72px" %>
        	<p id='friend'>cool.<br><br>Create a MattID.</p>
   	</div>
  
    <%= form_for(@user) do |f| %>  
  <div class="form-horizontal"> 
    	<div class="form-group">
		<label class="control-label col-sm-4 col-md-5 col-lg-5" for="first_name">First name</label>
		<div class="col-sm-5 col-md-3 col-lg-3">
			<%= f.text_field :first_name, :placeholder => 'make one up' %>
		</div> 
		</div>
<!--    <%= f.text_field :last_name, :placeholder => 'Last Name' %><br> -->
		<div class="form-group">
    	<label class="control-label  col-sm-4 col-md-5 col-lg-5" for="email">Email address</label>
	    <div class="col-sm-5 col-md-3 col-lg-3">
    		<%= f.email_field :email, :placeholder => 'enter junk email here' %>
    	</div>
		</div>

	<div class='account_info'>
	<div class="form-group">
    <label class="control-label  col-sm-4 col-md-5 col-lg-5" for="username">MattID</label>
    <div class="col-sm-5 col-md-3 col-lg-3">
	<%= f.text_field :username, :placeholder => 'choose one' %>
	</div>
	</div>
	<div class="form-group">
    <label class="control-label  col-sm-4 col-md-5 col-lg-5" for="password">Password</label>
    <div class="col-sm-5 col-md-3 col-lg-3">
    <%= f.password_field :password, :placeholder => "it'll be encrypted" %>
    </div>
    </div>
    </div>
  </div> 
  	<div class="form-group">
    <div class="col-sm-offset-4 col-md-offset-5 col-lg-offset-5  col-sm-5 col-md-3 col-lg-3">
    <%= f.submit "Create", class: "btn btn-default" %> 
    </div> 
    <% end %>
    </div>
</div>  